### ISSUE TITLE
Adding Multiple Lamps

### ISSUE THREAD

**Issue by WastedLoad** [DevJav/best_friend_lamp_arduino#11]
I am trying to create a group of five lamps.  I have finally got three lamps communicating.  When I select a color on lamp 1, lamp 2 replays the same color.  However, lamp 3 displays something different than the other two?  The code has not changed between the lamps except for the "LampID".  

I'm trying to understand the code and don't see where or why this would be?

**Comment by WastedLoad** [comment]
Another question for this thread.  Is it possible to assign a light color to a single lamp, then just selct the lamp by selecting a color that the end user wants to communicate with?

**Comment by hippsabq** [comment]
The key to using multiple lamps would be modifying the way that recVal and sendVal are handled. Right now only Lamps one and two will functionally work. Lamp 3 would be sending colors in the 30-38 (tens place is the lampID and the ones place is the color value) values which the other lamps wouldn't be looking for.....and would be looking to receive colors in the range that the other lamps wouldn't provide

I'll think about this, but not sure there is a direct way with the current code.

**Comment by WastedLoad** [comment]
Thank you
