### ISSUE TITLE
Issues With Touch Sensor

### ISSUE THREAD

**Issue by Josh029** [DevJav/best_friend_lamp_arduino#2]
So, I've uploaded the code to ensure everything works before I wire it up. The only thing I changed was the pins for the touch sensor and the lights, which I remapped to pins one and two (the touch sensor being on D2). The neopixel works without issues but the sensor always records high, even when it's not plugged in. It loops a few times and then reboots; the entire process takes about 5 seconds. I'm really confused as to what to do about this and I was wondering if you could offer any assistance? This is my first big arduino project so I'm not entirely sure what I'm doing, to be honest.

**Comment by Josh029** [comment]
Okay so I messed around with it a little bit and now I have an issue where the LEDS will only run through the RX pin no matter how I change the defined pins... Clueless as to what's going on here.

**Comment by DevJav** [comment]
> Okay so I messed around with it a little bit and now I have an issue where the LEDS will only run through the RX pin no matter how I change the defined pins... Clueless as to what's going on here.

Now you mention this I think that having the leds connected to RX was one of the requisites of the library but I can't remember why. I will take a look and update the instructions.

**Comment by Josh029** [comment]
Yeah they work perfectly through RX and I figured everything else out so
I'm definitely not messing with it lol thank you for the help!
