### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by McBigBob** [DevJav/best_friend_lamp_arduino#3]
Hello,
I'm new to ESP8266 and not very good at coding. But I was wondering is there a way to have the lamp stay always on and change colour when one of the two lamps is pressed? Also is there a way to reduce the brightness of the LEDs?

**Comment by DevJav** [comment]
Hi @McBigBob !

The first thing you ask is a feature that I'm planning to add, but I have to think first as I want it to be well integrated. However if you want it to be ALWAYS on, so there will be no other way to turn it off apart from disconecting it, you can add `Ilum100(SelectColor);` after the line `case 0:`, changing `SelectColor` to a number between 0->8. That way (in theory as I haven't tried) it will always be on with the selected color and change when you recieve/send a message.

To reduce the brightness you can change `int IntMax = 255;` to a lower value (it goes from 0 to 255).

**Comment by McBigBob** [comment]
Thanks for the fast response. I will be trying it out as soon as possible.
