### ISSUE TITLE
Problem with wifiManager

### ISSUE THREAD

**Issue by rianarang** [DevJav/best_friend_lamp_arduino#4]
I implemented the change from the comment linked in the readme but I am getting this error

Documents/Arduino/libraries/Adafruit_IO_Arduino/src/wifi/AdafruitIO_ESP8266.cpp:17:10: fatal error: WiFiManager.h: No such file or directory
   17 | #include <WiFiManager.h> // TJS: Hacked in for Mac's Klok

**Comment by DevJav** [comment]
@rianarang have you installed wifimanager from arduino ide?

**Comment by rianarang** [comment]
do you know which specific library is needed? Because a lot show up when I search wifimanager

**Comment by rianarang** [comment]
This fixed it thank you!
