### ISSUE TITLE
Connectivity to Adafruit IO

### ISSUE THREAD

**Issue by DavisIan22** [DevJav/best_friend_lamp_arduino#7]
I have both of my lamps reporting to Adafruit IO, but ever 30 seconds they reset, reconnect to my AP, and report to Adafruit IO. 
`Connecting to Adafruit IO..
Adafruit IO connected.

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffdc0 end: 3fffffc0 offset: 01a0
3fffff60:  3fffdad0 3ffef284 3ffef290 40201c28  
3fffff70:  00000000 00000000 feefeffe feefeffe  
3fffff80:  00000000 00000000 00000001 40100230  
3fffff90:  3fffdad0 00000000 3ffef540 3ffef554  
3fffffa0:  3fffdad0 00000000 3ffef540 40212a50  
3fffffb0:  feefeffe feefeffe 3ffe8600 40100da1  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v00074cd0
~ld
*wm:[1] AutoConnect 
*wm:[2] Connecting as wifi client... 
*wm:[2] setSTAConfig static ip not set, skipping 
*wm:[1] Connecting to SAVED AP: IOT
*wm:[1] connectTimeout not set, ESP waitForConnectResult... 
*wm:[2] Connection result: WL_CONNECTED
*wm:[1] AutoConnect: SUCCESS 
*wm:[1] STA IP Address: 192.168.3.54
Ready
IP address: 192.168.3.54

Connecting to Adafruit IO..
Adafruit IO connected.
`
Thats what keeps happening. I also have no LED output. When LED_Pin is defined, is that GPIO pin or physical pin?
I am using a Wemos D1 Mini.

**Comment by ilysium** [comment]
The problem is probably related to the wifi manager and the timeouts, I think you should try to add "yield()" to every loop. Hopefully that works ;)

**Comment by ilysium** [comment]
Also, for the lights, try using the "Adafruit_NeoPixel" library

**Comment by DevJav** [comment]
About the connection to Adafruit I really don't know, I think you'd better find an answer in a forum for that platform.

About the leds, the output pin must be the RX, and when defining it's the GPIO

**Comment by gobranj** [comment]
Not sure if you ended up finding a solution, but for what it's worth, I had the same exact problem you're describing. I think I had conflicting libraries installed, so a full reinstall of the Arduino IDE fixed it for me.

**Comment by gobranj** [comment]
> I have both of my lamps reporting to Adafruit IO, but ever 30 seconds they reset, reconnect to my AP, and report to Adafruit IO. `Connecting to Adafruit IO.. Adafruit IO connected.
> 
> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
> 
> Soft WDT reset
> 
> > > > stack>>>
> 
> ctx: cont sp: 3ffffdc0 end: 3fffffc0 offset: 01a0 3fffff60: 3fffdad0 3ffef284 3ffef290 40201c28 3fffff70: 00000000 00000000 feefeffe feefeffe 3fffff80: 00000000 00000000 00000001 40100230 3fffff90: 3fffdad0 00000000 3ffef540 3ffef554 3fffffa0: 3fffdad0 00000000 3ffef540 40212a50 3fffffb0: feefeffe feefeffe 3ffe8600 40100da1 <<<stack<<<
> 
> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
> 
> ets Jan 8 2013,rst cause:2, boot mode:(3,6)
> 
> load 0x4010f000, len 3460, room 16 tail 4 chksum 0xcc load 0x3fff20b8, len 40, room 4 tail 4 chksum 0xc9 csum 0xc9 v00074cd0 ~ld *wm:[1] AutoConnect *wm:[2] Connecting as wifi client... *wm:[2] setSTAConfig static ip not set, skipping *wm:[1] Connecting to SAVED AP: IOT *wm:[1] connectTimeout not set, ESP waitForConnectResult... *wm:[2] Connection result: WL_CONNECTED *wm:[1] AutoConnect: SUCCESS *wm:[1] STA IP Address: 192.168.3.54 Ready IP address: 192.168.3.54
> 
> Connecting to Adafruit IO.. Adafruit IO connected. ` Thats what keeps happening. I also have no LED output. When LED_Pin is defined, is that GPIO pin or physical pin? I am using a Wemos D1 Mini.


@Doubledeucedavis - Not sure if you ended up finding a solution, but for what it's worth, I had the same exact problem you're describing. I think I had conflicting libraries installed, so a full reinstall of the Arduino IDE fixed it for me.

**Comment by DavisIan22** [comment]
@DevJav I did end up getting it working a few days ago. I reinstalled everything and re-did all of my adafruit stuff as well and now it works. I didn't have to change any libraries or config files either!
